# Generated by Django 5.0.10 on 2024-12-25 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dump', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('timegate', models.CharField(max_length=255)),
                ('cdx_api', models.CharField(max_length=255)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('warc_size', models.FloatField()),
            ],
            options={
                'db_table': 'crawls',
            },
        ),
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotkey', models.CharField(max_length=255, unique=True)),
                ('coldkey', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'neurons',
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warc_file_ids', models.JSONField()),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('neuron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records_rel', to='subnets.neuron')),
            ],
            options={
                'db_table': 'task_records',
            },
        ),
        migrations.AddField(
            model_name='neuron',
            name='task_records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neurons_rel', to='subnets.taskrecord'),
        ),
        migrations.CreateModel(
            name='WarcFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warc_path', models.CharField(max_length=255, unique=True)),
                ('size', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('etag', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('completed', 'Completed'), ('failed', 'Failed')], default='available', max_length=20)),
                ('crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warc_files_rel', to='subnets.crawl')),
            ],
            options={
                'db_table': 'warc_files',
            },
        ),
        migrations.AddField(
            model_name='crawl',
            name='warc_files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawls_rel', to='subnets.warcfile'),
        ),
    ]
