# Generated by Django 5.0.10 on 2025-01-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dump', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('timegate', models.CharField(max_length=255)),
                ('cdx_api', models.CharField(max_length=255)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('warc_size', models.FloatField()),
            ],
            options={
                'db_table': 'crawls',
            },
        ),
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotkey', models.CharField(max_length=255, unique=True)),
                ('coldkey', models.CharField(max_length=255)),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'neurons',
            },
        ),
        migrations.CreateModel(
            name='WarcFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warc_path', models.CharField(max_length=255, unique=True)),
                ('size', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('etag', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('completed', 'Completed'), ('failed', 'Failed')], default='available', max_length=20)),
                ('crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warc_files_rel', to='subnets.crawl')),
            ],
            options={
                'db_table': 'warc_files',
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_block', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('hf_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records_rel', to='subnets.neuron')),
                ('warc_files', models.ManyToManyField(related_name='task_records', to='subnets.warcfile')),
            ],
            options={
                'db_table': 'task_records',
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subnets.neuron')),
                ('task_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subnets.taskrecord')),
            ],
            options={
                'db_table': 'score_records',
                'unique_together': {('validator', 'task_record')},
            },
        ),
    ]
