# Generated by Django 5.0.10 on 2024-12-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuron',
            name='coldkey',
            field=models.CharField(max_length=255),
        ),
    ]
