# Generated by Django 5.0.10 on 2024-12-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0002_alter_neuron_coldkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawl',
            name='warc_files',
        ),
    ]
