# Generated by Django 5.0.10 on 2024-12-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0003_remove_crawl_warc_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuron',
            name='task_records',
        ),
    ]
