# Generated by Django 5.0.10 on 2025-01-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0004_remove_neuron_task_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='request_time',
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='request_block',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
