# Generated by Django 5.0.10 on 2025-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0005_remove_taskrecord_request_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='hf_repo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
