# Generated by Django 5.0.10 on 2025-01-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0006_taskrecord_hf_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('signature', models.CharField(max_length=255)),
                ('neuron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subnets.neuron')),
                ('task_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subnets.taskrecord')),
            ],
            options={
                'db_table': 'score_records',
            },
        ),
    ]
