# Generated by Django 5.0.10 on 2025-01-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0007_scorerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorerecord',
            name='signature',
        ),
    ]
