# Generated by Django 5.0.10 on 2025-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0008_remove_scorerecord_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerecord',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
