# Generated by Django 5.0.10 on 2025-01-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0009_alter_scorerecord_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerecord',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
