# Generated by Django 5.0.10 on 2025-01-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0010_alter_scorerecord_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scorerecord',
            unique_together={('neuron', 'task_record')},
        ),
    ]
