# Generated by Django 5.0.10 on 2025-01-19 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0011_alter_scorerecord_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hf_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rows', models.IntegerField()),
                ('tokens', models.IntegerField()),
                ('crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='subnets.crawl')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
