# Generated by Django 5.0.10 on 2025-01-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0012_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
