# Generated by Django 5.0.10 on 2025-01-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0012_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='warc_file_ids',
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='warc_files',
            field=models.ManyToManyField(related_name='task_records', to='subnets.warcfile'),
        ),
    ]
