# Generated by Django 5.0.10 on 2025-01-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0013_remove_taskrecord_warc_file_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='score_records',
            field=models.ManyToManyField(blank=True, related_name='task_records', to='subnets.scorerecord'),
        ),
    ]
