# Generated by Django 5.0.10 on 2025-01-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0013_delete_product'),
        ('subnets', '0014_taskrecord_score_records'),
    ]

    operations = [
    ]
