# Generated by Django 5.0.10 on 2025-01-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0015_merge_20250124_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='score_records',
        ),
    ]
