# Generated by Django 5.0.10 on 2025-01-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0016_remove_taskrecord_score_records'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorerecord',
            old_name='neuron',
            new_name='validator',
        ),
        migrations.RenameField(
            model_name='taskrecord',
            old_name='neuron',
            new_name='miner',
        ),
        migrations.AlterUniqueTogether(
            name='scorerecord',
            unique_together={('validator', 'task_record')},
        ),
    ]
